/*
# Add missing tables: otp_codes, favorites, nutrition_history, meal_plans

## Overview
Creates the four tables that exist in migration files on disk but were not yet applied
to the live database.

## New Tables

### otp_codes
Stores hashed 6-digit one-time codes for custom email OTP sign-in.
Only accessible via service-role key (edge functions); RLS enabled with no policies
so the anon-key frontend cannot read or write it.
- id, email, code_hash (SHA-256), expires_at, consumed_at, created_at

### favorites
Per-user "liked" recipes (heart icon). Stores the full recipe payload as jsonb.
Owner-scoped RLS (4 policies, TO authenticated, auth.uid() = user_id).
- id, user_id (DEFAULT auth.uid()), recipe_title, recipe_data, created_at

### nutrition_history
Auto-log of every recipe generated by the user. Powers the Nutrition History page
and Dashboard recent-recipe cards.
Owner-scoped RLS (4 policies, TO authenticated, auth.uid() = user_id).
- id, user_id (DEFAULT auth.uid()), recipe_title, meal_type, recipe_data, nutrition, generated_at

### meal_plans
Persists generated multi-day meal plans (1day / 3day / 1week / 2week / 1month).
Owner-scoped RLS (4 policies, TO authenticated, auth.uid() = user_id).
- id, user_id (DEFAULT auth.uid()), duration, settings (jsonb), plan_data (jsonb), created_at

## Security
- RLS enabled on all four tables.
- otp_codes: no policies (service-role only).
- favorites, nutrition_history, meal_plans: 4-policy owner-scoped CRUD pattern.
*/

-- otp_codes
CREATE TABLE IF NOT EXISTS otp_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE otp_codes ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_otp_codes_email_created ON otp_codes(email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_otp_codes_expires ON otp_codes(expires_at);

-- favorites
CREATE TABLE IF NOT EXISTS favorites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_title text NOT NULL,
  recipe_data jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_favorites" ON favorites;
CREATE POLICY "select_own_favorites" ON favorites FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_favorites" ON favorites;
CREATE POLICY "insert_own_favorites" ON favorites FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_favorites" ON favorites;
CREATE POLICY "update_own_favorites" ON favorites FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_favorites" ON favorites;
CREATE POLICY "delete_own_favorites" ON favorites FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id, created_at DESC);

-- nutrition_history
CREATE TABLE IF NOT EXISTS nutrition_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_title text NOT NULL,
  meal_type text NOT NULL DEFAULT 'dinner',
  recipe_data jsonb NOT NULL,
  nutrition jsonb,
  generated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE nutrition_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_nutrition_history" ON nutrition_history;
CREATE POLICY "select_own_nutrition_history" ON nutrition_history FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_nutrition_history" ON nutrition_history;
CREATE POLICY "insert_own_nutrition_history" ON nutrition_history FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_nutrition_history" ON nutrition_history;
CREATE POLICY "update_own_nutrition_history" ON nutrition_history FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_nutrition_history" ON nutrition_history;
CREATE POLICY "delete_own_nutrition_history" ON nutrition_history FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_nutrition_history_user_id ON nutrition_history(user_id, generated_at DESC);

-- meal_plans
CREATE TABLE IF NOT EXISTS meal_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  duration text NOT NULL,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  plan_data jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE meal_plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_meal_plans" ON meal_plans;
CREATE POLICY "select_own_meal_plans" ON meal_plans FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_meal_plans" ON meal_plans;
CREATE POLICY "insert_own_meal_plans" ON meal_plans FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_meal_plans" ON meal_plans;
CREATE POLICY "update_own_meal_plans" ON meal_plans FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_meal_plans" ON meal_plans;
CREATE POLICY "delete_own_meal_plans" ON meal_plans FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_meal_plans_user_id ON meal_plans(user_id, created_at DESC);
